var testimonialsArray = [
['2011', 'Peter & Mary', '', 'Thank you for a wonderful stay in Ballyglass Cottage. You have resorted the building beautiful with so many of the original features. Its peace and tranquillity welcome you home after a busty day out. We ill definitely be back!'],
['2011', 'Noel & Michelle', '', 'We had and amaxing stay, the cottahe is stunnin and we will most certainly be back again!'],
['2011', 'The Becketts & Bridie,', '', 'Weve had a great week here in Ballyglass Cottage. Thank you very much for providing us with a wonderfully cosy abode. Well done with the restoration, its beautiful. Hope to be back again in the future.'],
['2011', 'Catriona', '', 'Well done guys - it cound be more comfortable and welcoming. I hope you reap the rewards of your labour and love.'],
['2011', 'Pauline & Mick Barrett', '', 'Lovely holiday, welcome break. Peace and quiet after festive season. Set us up for the new year. Many thanks for making us feel welcome. Hope to return very soon.'],
['2012', 'Mary McEvoy', '', 'Such a lovely place to stay, very friendly neighbours. Cottage is made feel just like home. Would love to rent pernanently. Thanks for everthing.'],
['2012', 'Gerry, Sarah, William & Gary', '', 'This is our second visit to this beautiful cottage and we will be back again. Ballyglass Thatched Cottage offers everything youd expect in a quiet country retreat.'],
['2012', 'Mark & Sonia. Karen & Barry', '', 'The cottage is so peaceful and well done. Thank you for a wonderful stay. The neighbours were friendly and helpful. Hope to be back soon.'],
['2012', 'Margerat & Rick', '', 'Beautiful cottage, very well situated for a peaceful break, well equiped for all your needs, pity the weather didnt match but ye cant control the weather. You made us feel very welcome and we hope to return.'],
['2012', 'Marian, Anna and Emma', '', 'We’ve spent 2 wonderful weeks in Ireland. You made us feel very welcome in your lovely cottage. Even the weather wasnt quite as bad as expected. Thank you so much.'],
['2012', 'Shane, Lindsey & Emily Mayo', '', 'Beautifuly cottage, wonderful holiday, what more could you ask for? Had and amzing time, stunning countryside, lovely cottage. Thank you. A brilliant week!! Weather was on our side and I will be returning for many more weeks! :)'],
['2012', 'Dee, Gilian, Maria, Hannah & Barney', '', 'We had and amazing stay and the bedrooms we lovely. Thanks for providing a lovely cottage which was so well provided for with towels etc. Hopefully we can have another chance to holiday here. '],
['2012', 'Susanne, Cova, Stephano & Marcelo', '', 'Thank you for our 2 week stay in this lovely cottage surrounded millions of sheep Maaaaaah. The chance of ran was great but with great luck we enjoyed the Irish sun. And the surroundings here at the cottage is totally quiet, we loved that very much.'],
['2012', 'Paul, Lisa, Matthew & Thomas Cheam', '', 'Thanks Niall & Ray. Had a nice stay here. Hoping to return again.'],
['2012', 'Chris, Teresa, Brend, Stacey, Matt and Amber', '', 'Thanks you for the use of your lovely cottage. We had a lovely time visiting the surrounding countryside and seeing family. The cottage is ideally situated and we enjoyed our visits from Ray.'],
['2012', 'Brian & Leigh', '', 'Had a good stay in Ballyglass. Nice and quiet. Would definitely recommend it to a friend.'],
['2012', 'Laura & John', '', 'Had a fantastic stay at Ballyglass. Very quiet and relaxing. Would definitely come back!'],
['2012', 'Michael, Mandy, Ben & Danny Whitley', '', 'We all had a wonderful relaxing stay here at Ballyglass Cottage. The cottage is lovely with everything we needed and felt just like home. We will definitely be back to stay again!'], ['2012', 'Sharon & Neil', '', 'Lovely cottage, lovely people, lovely holiday - Thank You!'],
['2012', 'Mary & Peter', '', 'Yet another wonderful stay. Such a great location for us to visit family in the Roscommon Balinasloe area. Cant believe the swallows are still here at the end of September!!'],
['2012', 'Pauline, Mick and family', '', 'Lovely stay, made us very welcome. Lovely views. Will return soon.'],
['2012', 'Thomas & familiy', '', 'Had a nice time except for the weather. Your cottage is lovely and it was good to meet you. Would like to come again.']
];